"""added city and state to GrowerOrDistributor

Revision ID: 14c9daa98328
Revises: 7db58ecd3a64
Create Date: 2025-12-22 11:09:24.263305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c9daa98328'
down_revision = '7db58ecd3a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grower_or_distributor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grower_or_distributor', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
