"""added is_master to customer model

Revision ID: 346fa96914f8
Revises: 385c98000c5c
Create Date: 2025-07-10 10:50:44.412341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346fa96914f8'
down_revision = '385c98000c5c'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('customer') as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_master',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('0')
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('is_master')

    # ### end Alembic commands ###
