"""added itemtotalcost table

Revision ID: 41153e68235b
Revises: d6bd1a06efc9
Create Date: 2025-06-11 12:48:31.964114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41153e68235b'
down_revision = 'd6bd1a06efc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_total_cost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('item_total_cost_item_id_item', 'company', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_total_cost', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')
        batch_op.drop_column('total_cost')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
