"""added name to airesponse table

Revision ID: a52b83ec0a35
Revises: 2c457cfe1270
Create Date: 2025-08-06 11:43:29.275741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52b83ec0a35'
down_revision = '2c457cfe1270'
branch_labels = None
depends_on = None


def upgrade():
    # Create new table with correct PK
    op.execute("""
    CREATE TABLE item_total_cost_new (
        id INTEGER PRIMARY KEY,
        item_id INTEGER NOT NULL,
        date DATE NOT NULL,
        ranch_cost FLOAT NOT NULL DEFAULT 0.0,
        total_cost FLOAT NOT NULL,
        packaging_cost FLOAT NOT NULL DEFAULT 0.0,
        raw_product_cost FLOAT NOT NULL DEFAULT 0.0,
        labor_cost FLOAT NOT NULL DEFAULT 0.0,
        designation_cost FLOAT NOT NULL DEFAULT 0.0,
        company_id INTEGER NOT NULL,
        FOREIGN KEY(item_id) REFERENCES item(id),
        FOREIGN KEY(company_id) REFERENCES company(id)
    )
    """)
    
    # Copy data
    op.execute("""
    INSERT INTO item_total_cost_new (id, item_id, date, ranch_cost, total_cost, 
                                    packaging_cost, raw_product_cost, labor_cost, 
                                    designation_cost, company_id)
    SELECT id, item_id, date, ranch_cost, total_cost, 
           packaging_cost, raw_product_cost, labor_cost, 
           designation_cost, company_id 
    FROM item_total_cost
    """)
    
    # Drop old table
    op.execute("DROP TABLE item_total_cost")
    
    # Rename new table
    op.execute("ALTER TABLE item_total_cost_new RENAME TO item_total_cost")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('ai_response', schema=None) as batch_op:
    #     batch_op.drop_column('name')
    pass

    # ### end Alembic commands ###
