"""date range for price sheets

Revision ID: ae328e84f072
Revises: e2e9b242d4c5
Create Date: 2026-01-30 10:45:34.285375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae328e84f072'
down_revision = 'e2e9b242d4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('valid_to', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_sheet', schema=None) as batch_op:
        batch_op.drop_column('valid_to')
        batch_op.drop_column('valid_from')

    # ### end Alembic commands ###
