"""moved item designation to be stored in item

Revision ID: fc15ed00327a
Revises: 6853e3aa2364
Create Date: 2025-06-04 11:45:53.648245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc15ed00327a'
down_revision = '6853e3aa2364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_designation', sa.Enum('SNACKPACK', 'RETAIL', 'FOODSERVICE', name='itemdesignation'), nullable=False, server_default='FOODSERVICE'))

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_column('item_designation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_designation', sa.VARCHAR(length=11), nullable=False))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('item_designation')

    # ### end Alembic commands ###
