"""made secondary table to hold relationship between items and their raw products

Revision ID: 18730eb035df
Revises: d53dd294cc57
Create Date: 2025-06-02 13:47:29.642266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18730eb035df'
down_revision = 'd53dd294cc57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_raw',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('raw_product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['raw_product_id'], ['raw_product.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'raw_product_id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('raw_product_ids')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_product_ids', sa.VARCHAR(length=100), nullable=True))

    op.drop_table('item_raw')
    # ### end Alembic commands ###
