"""changed pricehistory to store the price given to a customer of a certain item on a certain date

Revision ID: db1a98fa43f7
Revises: 41153e68235b
Create Date: 2025-06-12 10:48:02.168700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1a98fa43f7'
down_revision = '41153e68235b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.create_foreign_key('customer_id_fk', 'customer', ['customer_id'], ['id'])
        batch_op.drop_column('name')
        batch_op.drop_column('packaging_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packaging_cost', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('price')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
