"""added yield model

Revision ID: 0e7209fb0372
Revises: 8ab60b59e09c
Create Date: 2025-05-21 12:27:18.269952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7209fb0372'
down_revision = '8ab60b59e09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yield',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_product_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['raw_product_id'], ['raw_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_product', schema=None) as batch_op:
        batch_op.drop_column('weight')
        batch_op.drop_column('unit_of_weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_of_weight', sa.VARCHAR(length=8), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.FLOAT(), nullable=False))

    op.drop_table('yield')
    # ### end Alembic commands ###
