"""trying to fix issue with price sheet backup table

Revision ID: 2e3e0e682510
Revises: ae328e84f072
Create Date: 2026-02-25 17:54:19.745800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3e0e682510'
down_revision = 'ae328e84f072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_sheet_backup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_price_sheet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('backup_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['original_price_sheet_id'], ['price_sheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_sheet_backup_items',
    sa.Column('price_sheet_backup_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['price_sheet_backup_id'], ['price_sheet_backup.id'], ),
    sa.PrimaryKeyConstraint('price_sheet_backup_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_sheet_backup_items')
    op.drop_table('price_sheet_backup')
    # ### end Alembic commands ###
