"""added alternate code for item

Revision ID: 385c98000c5c
Revises: b62ba24f423d
Create Date: 2025-07-09 11:36:21.077267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385c98000c5c'
down_revision = 'b62ba24f423d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternate_code', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('alternate_code')

    # ### end Alembic commands ###
