"""added designation cost

Revision ID: 3986e9095e92
Revises: 78a35720b20e
Create Date: 2025-07-02 11:34:26.099655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3986e9095e92'
down_revision = '78a35720b20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designation_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_designation', sa.Enum('SNAKPAK', 'RETAIL', 'FOODSERVICE', name='itemdesignation'), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('designation_cost')
    # ### end Alembic commands ###
