"""added different parts of cost to be stored in ItemTotalCost

Revision ID: 41aa980324f8
Revises: db1a98fa43f7
Create Date: 2025-06-12 11:58:00.212167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41aa980324f8'
down_revision = 'db1a98fa43f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_total_cost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packaging_cost', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('raw_product_cost', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('labor_cost', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('designation_cost', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_total_cost', schema=None) as batch_op:
        batch_op.drop_column('designation_cost')
        batch_op.drop_column('labor_cost')
        batch_op.drop_column('raw_product_cost')
        batch_op.drop_column('packaging_cost')

    # ### end Alembic commands ###
