"""added price_paid to receiving log

Revision ID: 47ff6ddf7109
Revises: 410593a589cd
Create Date: 2026-01-08 12:41:41.751224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ff6ddf7109'
down_revision = '410593a589cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receiving_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_paid', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receiving_log', schema=None) as batch_op:
        batch_op.drop_column('price_paid')

    # ### end Alembic commands ###
