"""changed Item model

Revision ID: 5debce1f9ddf
Revises: e22f366945ec
Create Date: 2025-05-22 11:50:06.619234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5debce1f9ddf'
down_revision = 'e22f366945ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('code', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('packaging_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('item_designation', sa.Enum('SNACKPACK', 'RETAIL', 'FOODSERVICE', name='itemdesignation'), nullable=False))
        batch_op.add_column(sa.Column('raw_product_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ranch', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('case_weight', sa.Float(), nullable=False))
        #batch_op.drop_constraint(None, type_='foreignkey')
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_price_history_packaging_id_packaging', 'packaging', ['packaging_id'], ['id'])
        batch_op.create_foreign_key('fk_price_history_raw_product_id_raw_product', 'raw_product', ['raw_product_id'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('price')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])
        batch_op.create_foreign_key(None, 'item', ['item_id'], ['id'])
        batch_op.drop_column('case_weight')
        batch_op.drop_column('ranch')
        batch_op.drop_column('raw_product_id')
        batch_op.drop_column('item_designation')
        batch_op.drop_column('packaging_id')
        batch_op.drop_column('code')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
