"""got rid of weight in item since it now has case weight

Revision ID: 6853e3aa2364
Revises: 95c219eed593
Create Date: 2025-06-03 16:23:36.440424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6853e3aa2364'
down_revision = '95c219eed593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
