"""changed salesrecord datetime to sale_date

Revision ID: 6f9e3db93c42
Revises: a203474f2a49
Create Date: 2026-07-21 10:07:32.823932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9e3db93c42'
down_revision = 'a203474f2a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DATETIME(), nullable=False))
        batch_op.drop_column('sale_date')

    # ### end Alembic commands ###
