"""added receiving log and related tables

Revision ID: 7db58ecd3a64
Revises: 4b6aa9d4bb4f
Create Date: 2025-12-22 11:00:03.529015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db58ecd3a64'
down_revision = '4b6aa9d4bb4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grower_or_distributor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receiving_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_product_id', sa.Integer(), nullable=False),
    sa.Column('pack_size_unit', sa.String(length=50), nullable=False),
    sa.Column('pack_size', sa.Float(), nullable=False),
    sa.Column('brand_name_id', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('hold_or_used', sa.String(length=20), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('grower_or_distributor_id', sa.Integer(), nullable=False),
    sa.Column('country_of_origin', sa.String(length=100), nullable=False),
    sa.Column('received_by', sa.String(length=100), nullable=False),
    sa.Column('returned', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_name_id'], ['brand_name.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['grower_or_distributor_id'], ['grower_or_distributor.id'], ),
    sa.ForeignKeyConstraint(['raw_product_id'], ['raw_product.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receiving_log')
    op.drop_table('seller')
    op.drop_table('grower_or_distributor')
    op.drop_table('brand_name')
    # ### end Alembic commands ###
