"""changed cost datetime to date

Revision ID: 844db6be6c3a
Revises: 0e7209fb0372
Create Date: 2025-05-22 11:15:35.439450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844db6be6c3a'
down_revision = '0e7209fb0372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_history', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_history', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
