"""labor models

Revision ID: 8a547e06531c
Revises: added_expiration_to_api_keys
Create Date: 2026-06-26 11:45:16.276907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a547e06531c'
down_revision = 'added_expiration_to_api_keys'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('items', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Float(), nullable=False),
    sa.Column('labor_hours', sa.Float(), nullable=False),
    sa.Column('overtime_hours', sa.Float(), nullable=False),
    sa.Column('payroll_cost', sa.Float(), nullable=False),
    sa.Column('number_of_employees', sa.Integer(), nullable=False),
    sa.Column('labor_ratio', sa.Float(), nullable=False),
    sa.Column('sales_over_labor_cost', sa.Float(), nullable=False),
    sa.Column('average_man_hour_cost', sa.Float(), nullable=False),
    sa.Column('average_case_cost', sa.Float(), nullable=False),
    sa.Column('average_hours_per_employee', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('number_of_cases', sa.Integer(), nullable=False),
    sa.Column('number_of_rolls', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pay_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_by_item_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('item_designation_id', sa.Integer(), nullable=False),
    sa.Column('number_of_items', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Float(), nullable=False),
    sa.Column('average_price_per_item', sa.Float(), nullable=False),
    sa.Column('percent_of_total_sales', sa.Float(), nullable=False),
    sa.Column('percent_of_total_boxes', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['item_designation_id'], ['designation_cost.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_labor_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('pay_group_id', sa.Integer(), nullable=False),
    sa.Column('regular_hours', sa.Float(), nullable=False),
    sa.Column('overtime_hours', sa.Float(), nullable=False),
    sa.Column('pay', sa.Float(), nullable=False),
    sa.Column('percent_of_sales', sa.Float(), nullable=False),
    sa.Column('cost_per_hour', sa.Float(), nullable=False),
    sa.Column('number_in_pay_group', sa.Integer(), nullable=False),
    sa.Column('number_with_overtime', sa.Integer(), nullable=False),
    sa.Column('average_hours_per_employee', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['pay_group_id'], ['pay_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_user_id_created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notification_user_id_created_at', ['user_id', 'created_at'], unique=False)

    op.drop_table('weekly_labor_summary')
    op.drop_table('sales_by_item_type')
    op.drop_table('pay_groups')
    op.drop_table('film_usage')
    op.drop_table('daily_log')
    # ### end Alembic commands ###
