"""changed ranch and case weight to be in Item

Revision ID: 95c219eed593
Revises: a56953803d3c
Create Date: 2025-06-03 16:10:04.755114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c219eed593'
down_revision = 'a56953803d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("DROP TABLE IF EXISTS _alembic_tmp_item")


    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranch', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('case_weight', sa.Float(), nullable=False, server_default=sa.text('0.0')))

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        #batch_op.drop_constraint('None', type_='foreignkey')
        batch_op.drop_column('raw_product_id')
        batch_op.drop_column('ranch')
        batch_op.drop_column('case_weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_weight', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('ranch', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('raw_product_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'raw_product', ['raw_product_id'], ['id'])

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('case_weight')
        batch_op.drop_column('ranch')

    # ### end Alembic commands ###
