"""changes to item models

Revision ID: 9d666a76bb3d
Revises: 1a48f785dd0c
Create Date: 2025-05-29 12:33:48.736643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d666a76bb3d'
down_revision = '1a48f785dd0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('item_info_company_company_id', 'company', ['company_id'], ['id'])

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_code', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('packaging_cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.drop_constraint('fk_price_history_packaging_id_packaging', type_='foreignkey')
        batch_op.drop_column('code')
        batch_op.drop_column('packaging_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packaging_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=100), nullable=False))
        batch_op.create_foreign_key('fk_price_history_packaging_id_packaging', 'packaging', ['packaging_id'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('packaging_cost')
        batch_op.drop_column('item_code')

    with op.batch_alter_table('item_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
