"""raw_product_ids added to item

Revision ID: 9ff8d7742972
Revises: 9d666a76bb3d
Create Date: 2025-05-29 12:49:24.046490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff8d7742972'
down_revision = '9d666a76bb3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_product_ids', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('raw_product_ids')

    # ### end Alembic commands ###
