"""changes for labor app

Revision ID: a3de420f077e
Revises: 6f9e3db93c42
Create Date: 2026-08-13 10:37:18.196903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3de420f077e'
down_revision = '6f9e3db93c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('rule_triggered', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('dollar_impact', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomaly', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_entity_type'), ['entity_type'], unique=False)

    op.create_table('entity_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('window', sa.String(length=50), nullable=False),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('stddev', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_stat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_stat_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_stat_entity_type'), ['entity_type'], unique=False)

    op.create_table('job_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_table', sa.String(length=200), nullable=False),
    sa.Column('last_processed_id', sa.BigInteger(), nullable=True),
    sa.Column('last_processed_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_table')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_run')
    with op.batch_alter_table('entity_stat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_stat_entity_type'))
        batch_op.drop_index(batch_op.f('ix_entity_stat_entity_id'))

    op.drop_table('entity_stat')
    with op.batch_alter_table('anomaly', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_entity_type'))
        batch_op.drop_index(batch_op.f('ix_anomaly_entity_id'))

    op.drop_table('anomaly')
    # ### end Alembic commands ###
