"""changed pricehistory.item_code to be pricehistory.item_id because itemcode isn't unique

Revision ID: a56953803d3c
Revises: 18730eb035df
Create Date: 2025-06-03 16:05:43.512634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56953803d3c'
down_revision = '18730eb035df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_price_history_item_item_id', 'item', ['item_id'], ['id'])
        batch_op.drop_column('item_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_code', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
