"""Added expiration_to_api_keys

Revision ID: added_expiration_to_api_keys
Revises: f3b18a4c9d12
Create Date: 2026-05-08 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'added_expiration_to_api_keys'
down_revision = 'f3b18a4c9d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key', 'expires_at')
    # ### end Alembic commands ###
