"""added price_sheet_items table

Revision ID: b62ba24f423d
Revises: b864244dbcfd
Create Date: 2025-07-08 10:47:47.215549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62ba24f423d'
down_revision = 'b864244dbcfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_sheet_items',
    sa.Column('price_sheet_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['price_sheet_id'], ['price_sheet.id'], ),
    sa.PrimaryKeyConstraint('price_sheet_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_sheet_items')
    # ### end Alembic commands ###
