"""supplies inventory and inventory models

Revision ID: c66d73e9c4a0
Revises: 2e3e0e682510
Create Date: 2026-03-06 10:31:42.483304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66d73e9c4a0'
down_revision = '2e3e0e682510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'inventory_session' not in existing_tables:
        op.create_table('inventory_session',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('label', sa.String(length=200), nullable=True),
        sa.Column('counted_by', sa.String(length=200), nullable=True),
        sa.Column('notes', sa.String(length=500), nullable=True),
        sa.Column('submitted_at', sa.DateTime(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if 'supply' not in existing_tables:
        op.create_table('supply',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('unit', sa.String(length=50), nullable=False),
        sa.Column('category', sa.String(length=100), nullable=True),
        sa.Column('notes', sa.String(length=500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if 'supply_inventory_count' not in existing_tables:
        op.create_table('supply_inventory_count',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=True),
        sa.Column('supply_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('count_date', sa.DateTime(), nullable=False),
        sa.Column('counted_by', sa.String(length=200), nullable=True),
        sa.Column('notes', sa.String(length=500), nullable=True),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
        sa.ForeignKeyConstraint(['session_id'], ['inventory_session.id'], ),
        sa.ForeignKeyConstraint(['supply_id'], ['supply.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('supply_inventory_count') as batch_op:
            batch_op.create_index(batch_op.f('ix_supply_inventory_count_session_id'), ['session_id'], unique=False)

    # Add session_id to inventory_count if it doesn't already exist
    inv_count_cols = [c['name'] for c in inspector.get_columns('inventory_count')]
    if 'session_id' not in inv_count_cols:
        with op.batch_alter_table('inventory_count') as batch_op:
            batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
            batch_op.create_index(batch_op.f('ix_inventory_count_session_id'), ['session_id'], unique=False)
            batch_op.create_foreign_key('fk_inventory_count_session_id', 'inventory_session', ['session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_count', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_inventory_count_session_id'))
        batch_op.drop_column('session_id')

    with op.batch_alter_table('supply_inventory_count', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supply_inventory_count_session_id'))

    op.drop_table('supply_inventory_count')
    op.drop_table('supply')
    op.drop_table('inventory_session')
    # ### end Alembic commands ###
