"""got rid of yield model

Revision ID: e22f366945ec
Revises: 844db6be6c3a
Create Date: 2025-05-22 11:31:06.003483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22f366945ec'
down_revision = '844db6be6c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yield')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yield',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('raw_product_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['raw_product_id'], ['raw_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
