"""added ItemInfo model


Revision ID: e6152920115e
Revises: 5debce1f9ddf
Create Date: 2025-05-22 12:07:11.582648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6152920115e'
down_revision = '5debce1f9ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_yield', sa.Float(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('labor_hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_info')
    # ### end Alembic commands ###
