"""added raw_product.lot_code

Revision ID: e84bede56e8e
Revises: c66d73e9c4a0
Create Date: 2026-04-17 11:38:10.628572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84bede56e8e'
down_revision = 'c66d73e9c4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot_code', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_product', schema=None) as batch_op:
        batch_op.drop_column('lot_code')

    # ### end Alembic commands ###
