"""added cost to RanchPrice

Revision ID: 23f668878d0a
Revises: 4ab3e7f0eb06
Create Date: 2025-06-24 10:51:52.999092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f668878d0a'
down_revision = '4ab3e7f0eb06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranch_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranch_price', schema=None) as batch_op:
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
