"""added name to airesponse table

Revision ID: a52b83ec0a35
Revises: 2c457cfe1270
Create Date: 2025-08-06 11:43:29.275741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52b83ec0a35'
down_revision = '2c457cfe1270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('item_total_cost', sa.Column('ranch_cost', sa.Float(), nullable=False, server_default='0.0'))
    op.alter_column('item_total_cost', 'ranch_cost', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_response', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
