"""empty message

Revision ID: dfb45aa02a84
Revises: 
Create Date: 2025-05-14 13:38:28.236883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb45aa02a84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packaging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('packaging_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packaging_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('packaging_id', sa.Integer(), nullable=False),
    sa.Column('box_cost', sa.Float(), nullable=False),
    sa.Column('bag_cost', sa.Float(), nullable=False),
    sa.Column('tray_andor_chemical_cost', sa.Float(), nullable=False),
    sa.Column('label_andor_tape_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['packaging_id'], ['packaging.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packaging_cost')
    op.drop_table('packaging')
    # ### end Alembic commands ###
